/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rodolfohahn.locadora.controller.view;

/**
 *
 * @author Bolinho
 */
public class JanelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form JanelaMenu
     */
    public JanelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuFuncionario = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenuItem();
        menuFilme = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuFuncionarioL = new javax.swing.JMenuItem();
        menuClienteL = new javax.swing.JMenuItem();
        menuCategoriaL = new javax.swing.JMenuItem();
        menuFilmeL = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuFecharPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rodolfohahn/locadora/controller/view/imagens/i_menu.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        jMenu1.setText("Cadastrar");
        jMenu1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N

        menuFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuFuncionario.setText("Funcionario");
        menuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuFuncionario);

        menuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuCliente);

        menuCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCategoria.setText("Categoria");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(menuCategoria);

        menuFilme.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuFilme.setText("Filme");
        menuFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFilmeActionPerformed(evt);
            }
        });
        jMenu1.add(menuFilme);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listar");
        jMenu2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N

        menuFuncionarioL.setText("Funcionario");
        menuFuncionarioL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioLActionPerformed(evt);
            }
        });
        jMenu2.add(menuFuncionarioL);

        menuClienteL.setText("Cliente");
        menuClienteL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteLActionPerformed(evt);
            }
        });
        jMenu2.add(menuClienteL);

        menuCategoriaL.setText("Categoria");
        menuCategoriaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaLActionPerformed(evt);
            }
        });
        jMenu2.add(menuCategoriaL);

        menuFilmeL.setText("Filme");
        menuFilmeL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFilmeLActionPerformed(evt);
            }
        });
        jMenu2.add(menuFilmeL);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");
        jMenu3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N

        menuFecharPrograma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuFecharPrograma.setText("Fechar Programa");
        menuFecharPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFecharProgramaActionPerformed(evt);
            }
        });
        jMenu3.add(menuFecharPrograma);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFilmeActionPerformed
        FilmeCadastro fic = new FilmeCadastro();
        fic.setLocationRelativeTo(null);
        fic.setVisible(true);
    }//GEN-LAST:event_menuFilmeActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed
        FuncionarioCadastro fuc = new FuncionarioCadastro();
        fuc.setLocationRelativeTo(null);
        fuc.setVisible(true);
    }//GEN-LAST:event_menuFuncionarioActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        ClienteCadastro cl = new ClienteCadastro();
        cl.setLocationRelativeTo(null);
        cl.setVisible(true);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        CadastroCategoria cac = new CadastroCategoria();
        cac.setLocationRelativeTo(null);
        cac.setVisible(true);
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuFuncionarioLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioLActionPerformed
        FuncionarioListar fl = new FuncionarioListar();
        fl.setLocationRelativeTo(null);
        fl.setVisible(true);
    }//GEN-LAST:event_menuFuncionarioLActionPerformed

    private void menuClienteLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteLActionPerformed
        ClienteListar cl = new ClienteListar();
        cl.setLocationRelativeTo(null);
        cl.setVisible(true);
    }//GEN-LAST:event_menuClienteLActionPerformed

    private void menuCategoriaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaLActionPerformed
        CategoriaListar cl = new CategoriaListar();
        cl.setLocationRelativeTo(null);
        cl.setVisible(true);
    }//GEN-LAST:event_menuCategoriaLActionPerformed

    private void menuFilmeLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFilmeLActionPerformed
        FilmeListar fl = new FilmeListar();
        fl.setLocationRelativeTo(null);
        fl.setVisible(true);
    }//GEN-LAST:event_menuFilmeLActionPerformed

    private void menuFecharProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFecharProgramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuFecharProgramaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JanelaMenu().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuCategoriaL;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuClienteL;
    private javax.swing.JMenuItem menuFecharPrograma;
    private javax.swing.JMenuItem menuFilme;
    private javax.swing.JMenuItem menuFilmeL;
    private javax.swing.JMenuItem menuFuncionario;
    private javax.swing.JMenuItem menuFuncionarioL;
    // End of variables declaration//GEN-END:variables
}
